services:
  db:
    image: mysql:8.0
    container_name: cache-system-db
    env_file:
      - /Users/hasingh/Downloads/capstone/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: {}
